//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDVR.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class settingsForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal settingsForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarDVR.Forms.settingsForm", typeof(settingsForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Point amountOfFiles_Location {
            get {
                object obj = ResourceManager.GetObject("amountOfFiles.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size amountOfFiles_Size {
            get {
                object obj = ResourceManager.GetObject("amountOfFiles.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int amountOfFiles_TabIndex {
            get {
                object obj = ResourceManager.GetObject("amountOfFiles.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static bool autostartRecording_AutoSize {
            get {
                object obj = ResourceManager.GetObject("autostartRecording.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Drawing.Point autostartRecording_Location {
            get {
                object obj = ResourceManager.GetObject("autostartRecording.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size autostartRecording_Size {
            get {
                object obj = ResourceManager.GetObject("autostartRecording.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int autostartRecording_TabIndex {
            get {
                object obj = ResourceManager.GetObject("autostartRecording.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enable autostart recording.
        /// </summary>
        public static string autostartRecording_Text {
            get {
                return ResourceManager.GetString("autostartRecording.Text", resourceCulture);
            }
        }
        
        public static System.Drawing.Point aviDuration_Location {
            get {
                object obj = ResourceManager.GetObject("aviDuration.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size aviDuration_Size {
            get {
                object obj = ResourceManager.GetObject("aviDuration.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int aviDuration_TabIndex {
            get {
                object obj = ResourceManager.GetObject("aviDuration.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static System.Drawing.Point backupFilesAmount_Location {
            get {
                object obj = ResourceManager.GetObject("backupFilesAmount.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size backupFilesAmount_Size {
            get {
                object obj = ResourceManager.GetObject("backupFilesAmount.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int backupFilesAmount_TabIndex {
            get {
                object obj = ResourceManager.GetObject("backupFilesAmount.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static System.Windows.Forms.AnchorStyles button1_Anchor {
            get {
                object obj = ResourceManager.GetObject("button1.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        public static System.Windows.Forms.FlatStyle button1_FlatStyle {
            get {
                object obj = ResourceManager.GetObject("button1.FlatStyle", resourceCulture);
                return ((System.Windows.Forms.FlatStyle)(obj));
            }
        }
        
        public static System.Drawing.Point button1_Location {
            get {
                object obj = ResourceManager.GetObject("button1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size button1_Size {
            get {
                object obj = ResourceManager.GetObject("button1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int button1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("button1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string button1_Text {
            get {
                return ResourceManager.GetString("button1.Text", resourceCulture);
            }
        }
        
        public static System.Windows.Forms.FlatStyle buttonBackColor_FlatStyle {
            get {
                object obj = ResourceManager.GetObject("buttonBackColor.FlatStyle", resourceCulture);
                return ((System.Windows.Forms.FlatStyle)(obj));
            }
        }
        
        public static System.Windows.Forms.ImeMode buttonBackColor_ImeMode {
            get {
                object obj = ResourceManager.GetObject("buttonBackColor.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        public static System.Drawing.Point buttonBackColor_Location {
            get {
                object obj = ResourceManager.GetObject("buttonBackColor.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size buttonBackColor_Size {
            get {
                object obj = ResourceManager.GetObject("buttonBackColor.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int buttonBackColor_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonBackColor.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back.
        /// </summary>
        public static string buttonBackColor_Text {
            get {
                return ResourceManager.GetString("buttonBackColor.Text", resourceCulture);
            }
        }
        
        public static System.Windows.Forms.AnchorStyles buttonBrowse_Anchor {
            get {
                object obj = ResourceManager.GetObject("buttonBrowse.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        public static System.Windows.Forms.FlatStyle buttonBrowse_FlatStyle {
            get {
                object obj = ResourceManager.GetObject("buttonBrowse.FlatStyle", resourceCulture);
                return ((System.Windows.Forms.FlatStyle)(obj));
            }
        }
        
        public static System.Drawing.Point buttonBrowse_Location {
            get {
                object obj = ResourceManager.GetObject("buttonBrowse.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size buttonBrowse_Size {
            get {
                object obj = ResourceManager.GetObject("buttonBrowse.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int buttonBrowse_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonBrowse.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string buttonBrowse_Text {
            get {
                return ResourceManager.GetString("buttonBrowse.Text", resourceCulture);
            }
        }
        
        public static System.Windows.Forms.AnchorStyles buttonBrowseBackup_Anchor {
            get {
                object obj = ResourceManager.GetObject("buttonBrowseBackup.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        public static System.Windows.Forms.FlatStyle buttonBrowseBackup_FlatStyle {
            get {
                object obj = ResourceManager.GetObject("buttonBrowseBackup.FlatStyle", resourceCulture);
                return ((System.Windows.Forms.FlatStyle)(obj));
            }
        }
        
        public static System.Windows.Forms.ImeMode buttonBrowseBackup_ImeMode {
            get {
                object obj = ResourceManager.GetObject("buttonBrowseBackup.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        public static System.Drawing.Point buttonBrowseBackup_Location {
            get {
                object obj = ResourceManager.GetObject("buttonBrowseBackup.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size buttonBrowseBackup_Size {
            get {
                object obj = ResourceManager.GetObject("buttonBrowseBackup.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int buttonBrowseBackup_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonBrowseBackup.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string buttonBrowseBackup_Text {
            get {
                return ResourceManager.GetString("buttonBrowseBackup.Text", resourceCulture);
            }
        }
        
        public static System.Windows.Forms.AnchorStyles buttonOk_Anchor {
            get {
                object obj = ResourceManager.GetObject("buttonOk.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        public static System.Windows.Forms.FlatStyle buttonOk_FlatStyle {
            get {
                object obj = ResourceManager.GetObject("buttonOk.FlatStyle", resourceCulture);
                return ((System.Windows.Forms.FlatStyle)(obj));
            }
        }
        
        public static System.Drawing.Point buttonOk_Location {
            get {
                object obj = ResourceManager.GetObject("buttonOk.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size buttonOk_Size {
            get {
                object obj = ResourceManager.GetObject("buttonOk.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int buttonOk_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonOk.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string buttonOk_Text {
            get {
                return ResourceManager.GetString("buttonOk.Text", resourceCulture);
            }
        }
        
        public static System.Windows.Forms.FlatStyle buttonSettings_FlatStyle {
            get {
                object obj = ResourceManager.GetObject("buttonSettings.FlatStyle", resourceCulture);
                return ((System.Windows.Forms.FlatStyle)(obj));
            }
        }
        
        public static System.Drawing.Point buttonSettings_Location {
            get {
                object obj = ResourceManager.GetObject("buttonSettings.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size buttonSettings_Size {
            get {
                object obj = ResourceManager.GetObject("buttonSettings.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int buttonSettings_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonSettings.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string buttonSettings_Text {
            get {
                return ResourceManager.GetString("buttonSettings.Text", resourceCulture);
            }
        }
        
        public static System.Windows.Forms.FlatStyle buttonTextColor_FlatStyle {
            get {
                object obj = ResourceManager.GetObject("buttonTextColor.FlatStyle", resourceCulture);
                return ((System.Windows.Forms.FlatStyle)(obj));
            }
        }
        
        public static System.Drawing.Point buttonTextColor_Location {
            get {
                object obj = ResourceManager.GetObject("buttonTextColor.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size buttonTextColor_Size {
            get {
                object obj = ResourceManager.GetObject("buttonTextColor.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int buttonTextColor_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonTextColor.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text.
        /// </summary>
        public static string buttonTextColor_Text {
            get {
                return ResourceManager.GetString("buttonTextColor.Text", resourceCulture);
            }
        }
        
        public static System.Drawing.Point camFps_Location {
            get {
                object obj = ResourceManager.GetObject("camFps.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size camFps_Size {
            get {
                object obj = ResourceManager.GetObject("camFps.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int camFps_TabIndex {
            get {
                object obj = ResourceManager.GetObject("camFps.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static System.Drawing.Point colorDialog_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("colorDialog.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string comboLanguage_Items {
            get {
                return ResourceManager.GetString("comboLanguage.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string comboLanguage_Items1 {
            get {
                return ResourceManager.GetString("comboLanguage.Items1", resourceCulture);
            }
        }
        
        public static System.Drawing.Point comboLanguage_Location {
            get {
                object obj = ResourceManager.GetObject("comboLanguage.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size comboLanguage_Size {
            get {
                object obj = ResourceManager.GetObject("comboLanguage.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int comboLanguage_TabIndex {
            get {
                object obj = ResourceManager.GetObject("comboLanguage.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static System.Drawing.Point comboResolution_Location {
            get {
                object obj = ResourceManager.GetObject("comboResolution.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size comboResolution_Size {
            get {
                object obj = ResourceManager.GetObject("comboResolution.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int comboResolution_TabIndex {
            get {
                object obj = ResourceManager.GetObject("comboResolution.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static System.Drawing.Point comboRotateAngle_Location {
            get {
                object obj = ResourceManager.GetObject("comboRotateAngle.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size comboRotateAngle_Size {
            get {
                object obj = ResourceManager.GetObject("comboRotateAngle.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int comboRotateAngle_TabIndex {
            get {
                object obj = ResourceManager.GetObject("comboRotateAngle.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static System.Drawing.Point delayBeforeStart_Location {
            get {
                object obj = ResourceManager.GetObject("delayBeforeStart.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size delayBeforeStart_Size {
            get {
                object obj = ResourceManager.GetObject("delayBeforeStart.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int delayBeforeStart_TabIndex {
            get {
                object obj = ResourceManager.GetObject("delayBeforeStart.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static bool dontDisplayWhenAppInactive_AutoSize {
            get {
                object obj = ResourceManager.GetObject("dontDisplayWhenAppInactive.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Windows.Forms.ImeMode dontDisplayWhenAppInactive_ImeMode {
            get {
                object obj = ResourceManager.GetObject("dontDisplayWhenAppInactive.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        public static System.Drawing.Point dontDisplayWhenAppInactive_Location {
            get {
                object obj = ResourceManager.GetObject("dontDisplayWhenAppInactive.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size dontDisplayWhenAppInactive_Size {
            get {
                object obj = ResourceManager.GetObject("dontDisplayWhenAppInactive.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int dontDisplayWhenAppInactive_TabIndex {
            get {
                object obj = ResourceManager.GetObject("dontDisplayWhenAppInactive.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to don&apos;t display when inactive
        ///(less CPU usage).
        /// </summary>
        public static string dontDisplayWhenAppInactive_Text {
            get {
                return ResourceManager.GetString("dontDisplayWhenAppInactive.Text", resourceCulture);
            }
        }
        
        public static bool enableGps_AutoSize {
            get {
                object obj = ResourceManager.GetObject("enableGps.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Drawing.Point enableGps_Location {
            get {
                object obj = ResourceManager.GetObject("enableGps.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size enableGps_Size {
            get {
                object obj = ResourceManager.GetObject("enableGps.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int enableGps_TabIndex {
            get {
                object obj = ResourceManager.GetObject("enableGps.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enable.
        /// </summary>
        public static string enableGps_Text {
            get {
                return ResourceManager.GetString("enableGps.Text", resourceCulture);
            }
        }
        
        public static bool enableRotate_AutoSize {
            get {
                object obj = ResourceManager.GetObject("enableRotate.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Drawing.Point enableRotate_Location {
            get {
                object obj = ResourceManager.GetObject("enableRotate.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size enableRotate_Size {
            get {
                object obj = ResourceManager.GetObject("enableRotate.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int enableRotate_TabIndex {
            get {
                object obj = ResourceManager.GetObject("enableRotate.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rotate video.
        /// </summary>
        public static string enableRotate_Text {
            get {
                return ResourceManager.GetString("enableRotate.Text", resourceCulture);
            }
        }
        
        public static System.Drawing.Point gbAutostart_Location {
            get {
                object obj = ResourceManager.GetObject("gbAutostart.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size gbAutostart_Size {
            get {
                object obj = ResourceManager.GetObject("gbAutostart.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int gbAutostart_TabIndex {
            get {
                object obj = ResourceManager.GetObject("gbAutostart.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video output.
        /// </summary>
        public static string gbAutostart_Text {
            get {
                return ResourceManager.GetString("gbAutostart.Text", resourceCulture);
            }
        }
        
        public static System.Drawing.Point groupVideoArchive_Location {
            get {
                object obj = ResourceManager.GetObject("groupVideoArchive.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size groupVideoArchive_Size {
            get {
                object obj = ResourceManager.GetObject("groupVideoArchive.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int groupVideoArchive_TabIndex {
            get {
                object obj = ResourceManager.GetObject("groupVideoArchive.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video archive.
        /// </summary>
        public static string groupVideoArchive_Text {
            get {
                return ResourceManager.GetString("groupVideoArchive.Text", resourceCulture);
            }
        }
        
        public static bool hideMouse_AutoSize {
            get {
                object obj = ResourceManager.GetObject("hideMouse.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Drawing.Point hideMouse_Location {
            get {
                object obj = ResourceManager.GetObject("hideMouse.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size hideMouse_Size {
            get {
                object obj = ResourceManager.GetObject("hideMouse.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int hideMouse_TabIndex {
            get {
                object obj = ResourceManager.GetObject("hideMouse.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide mouse cursor.
        /// </summary>
        public static string hideMouse_Text {
            get {
                return ResourceManager.GetString("hideMouse.Text", resourceCulture);
            }
        }
        
        public static bool label1_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label1.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Drawing.Point label1_Location {
            get {
                object obj = ResourceManager.GetObject("label1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size label1_Size {
            get {
                object obj = ResourceManager.GetObject("label1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int label1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fps.
        /// </summary>
        public static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        public static bool label2_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label2.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Drawing.Point label2_Location {
            get {
                object obj = ResourceManager.GetObject("label2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size label2_Size {
            get {
                object obj = ResourceManager.GetObject("label2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int label2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to output rate.
        /// </summary>
        public static string label2_Text {
            get {
                return ResourceManager.GetString("label2.Text", resourceCulture);
            }
        }
        
        public static bool label3_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label3.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Windows.Forms.ImeMode label3_ImeMode {
            get {
                object obj = ResourceManager.GetObject("label3.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        public static System.Drawing.Point label3_Location {
            get {
                object obj = ResourceManager.GetObject("label3.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size label3_Size {
            get {
                object obj = ResourceManager.GetObject("label3.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int label3_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label3.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to path for quick backup.
        /// </summary>
        public static string label3_Text {
            get {
                return ResourceManager.GetString("label3.Text", resourceCulture);
            }
        }
        
        public static bool labelBackupFiles_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelBackupFiles.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Drawing.Point labelBackupFiles_Location {
            get {
                object obj = ResourceManager.GetObject("labelBackupFiles.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size labelBackupFiles_Size {
            get {
                object obj = ResourceManager.GetObject("labelBackupFiles.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int labelBackupFiles_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelBackupFiles.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files amount to backup.
        /// </summary>
        public static string labelBackupFiles_Text {
            get {
                return ResourceManager.GetString("labelBackupFiles.Text", resourceCulture);
            }
        }
        
        public static bool labelBaudRate_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelBaudRate.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Drawing.Point labelBaudRate_Location {
            get {
                object obj = ResourceManager.GetObject("labelBaudRate.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size labelBaudRate_Size {
            get {
                object obj = ResourceManager.GetObject("labelBaudRate.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int labelBaudRate_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelBaudRate.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to baud rate.
        /// </summary>
        public static string labelBaudRate_Text {
            get {
                return ResourceManager.GetString("labelBaudRate.Text", resourceCulture);
            }
        }
        
        public static bool labelColors_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelColors.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Drawing.Point labelColors_Location {
            get {
                object obj = ResourceManager.GetObject("labelColors.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size labelColors_Size {
            get {
                object obj = ResourceManager.GetObject("labelColors.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int labelColors_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelColors.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to colors.
        /// </summary>
        public static string labelColors_Text {
            get {
                return ResourceManager.GetString("labelColors.Text", resourceCulture);
            }
        }
        
        public static bool labelDegrees_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelDegrees.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Drawing.Point labelDegrees_Location {
            get {
                object obj = ResourceManager.GetObject("labelDegrees.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size labelDegrees_Size {
            get {
                object obj = ResourceManager.GetObject("labelDegrees.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int labelDegrees_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelDegrees.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to degrees.
        /// </summary>
        public static string labelDegrees_Text {
            get {
                return ResourceManager.GetString("labelDegrees.Text", resourceCulture);
            }
        }
        
        public static bool labelDelayAutostart_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelDelayAutostart.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Drawing.Point labelDelayAutostart_Location {
            get {
                object obj = ResourceManager.GetObject("labelDelayAutostart.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size labelDelayAutostart_Size {
            get {
                object obj = ResourceManager.GetObject("labelDelayAutostart.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int labelDelayAutostart_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelDelayAutostart.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delay before autostart (sec).
        /// </summary>
        public static string labelDelayAutostart_Text {
            get {
                return ResourceManager.GetString("labelDelayAutostart.Text", resourceCulture);
            }
        }
        
        public static bool labelFrameRate_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelFrameRate.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Windows.Forms.ImeMode labelFrameRate_ImeMode {
            get {
                object obj = ResourceManager.GetObject("labelFrameRate.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        public static System.Drawing.Point labelFrameRate_Location {
            get {
                object obj = ResourceManager.GetObject("labelFrameRate.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size labelFrameRate_Size {
            get {
                object obj = ResourceManager.GetObject("labelFrameRate.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int labelFrameRate_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelFrameRate.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frame rate.
        /// </summary>
        public static string labelFrameRate_Text {
            get {
                return ResourceManager.GetString("labelFrameRate.Text", resourceCulture);
            }
        }
        
        public static bool labelLanguage_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelLanguage.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Windows.Forms.ImeMode labelLanguage_ImeMode {
            get {
                object obj = ResourceManager.GetObject("labelLanguage.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        public static System.Drawing.Point labelLanguage_Location {
            get {
                object obj = ResourceManager.GetObject("labelLanguage.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size labelLanguage_Size {
            get {
                object obj = ResourceManager.GetObject("labelLanguage.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int labelLanguage_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelLanguage.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language.
        /// </summary>
        public static string labelLanguage_Text {
            get {
                return ResourceManager.GetString("labelLanguage.Text", resourceCulture);
            }
        }
        
        public static bool labelMinutesOnEachFile_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelMinutesOnEachFile.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Drawing.Point labelMinutesOnEachFile_Location {
            get {
                object obj = ResourceManager.GetObject("labelMinutesOnEachFile.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size labelMinutesOnEachFile_Size {
            get {
                object obj = ResourceManager.GetObject("labelMinutesOnEachFile.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int labelMinutesOnEachFile_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelMinutesOnEachFile.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duration of each file (min).
        /// </summary>
        public static string labelMinutesOnEachFile_Text {
            get {
                return ResourceManager.GetString("labelMinutesOnEachFile.Text", resourceCulture);
            }
        }
        
        public static bool labelPath_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelPath.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Drawing.Point labelPath_Location {
            get {
                object obj = ResourceManager.GetObject("labelPath.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size labelPath_Size {
            get {
                object obj = ResourceManager.GetObject("labelPath.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int labelPath_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelPath.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to path to store video files to.
        /// </summary>
        public static string labelPath_Text {
            get {
                return ResourceManager.GetString("labelPath.Text", resourceCulture);
            }
        }
        
        public static bool labelResolution_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelResolution.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Drawing.Point labelResolution_Location {
            get {
                object obj = ResourceManager.GetObject("labelResolution.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size labelResolution_Size {
            get {
                object obj = ResourceManager.GetObject("labelResolution.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int labelResolution_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelResolution.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resolution.
        /// </summary>
        public static string labelResolution_Text {
            get {
                return ResourceManager.GetString("labelResolution.Text", resourceCulture);
            }
        }
        
        public static bool labelSelectedCodec_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelSelectedCodec.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Windows.Forms.ImeMode labelSelectedCodec_ImeMode {
            get {
                object obj = ResourceManager.GetObject("labelSelectedCodec.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        public static System.Drawing.Point labelSelectedCodec_Location {
            get {
                object obj = ResourceManager.GetObject("labelSelectedCodec.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size labelSelectedCodec_Size {
            get {
                object obj = ResourceManager.GetObject("labelSelectedCodec.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int labelSelectedCodec_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelSelectedCodec.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        public static string labelSelectedCodec_Text {
            get {
                return ResourceManager.GetString("labelSelectedCodec.Text", resourceCulture);
            }
        }
        
        public static bool labelSelectedCodecTitle_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelSelectedCodecTitle.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Drawing.Point labelSelectedCodecTitle_Location {
            get {
                object obj = ResourceManager.GetObject("labelSelectedCodecTitle.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size labelSelectedCodecTitle_Size {
            get {
                object obj = ResourceManager.GetObject("labelSelectedCodecTitle.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int labelSelectedCodecTitle_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelSelectedCodecTitle.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected codec:.
        /// </summary>
        public static string labelSelectedCodecTitle_Text {
            get {
                return ResourceManager.GetString("labelSelectedCodecTitle.Text", resourceCulture);
            }
        }
        
        public static bool labelStoreFiles_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelStoreFiles.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Drawing.Point labelStoreFiles_Location {
            get {
                object obj = ResourceManager.GetObject("labelStoreFiles.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size labelStoreFiles_Size {
            get {
                object obj = ResourceManager.GetObject("labelStoreFiles.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int labelStoreFiles_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelStoreFiles.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files amount in archive.
        /// </summary>
        public static string labelStoreFiles_Text {
            get {
                return ResourceManager.GetString("labelStoreFiles.Text", resourceCulture);
            }
        }
        
        public static System.Windows.Forms.DockStyle labelTestColor_Dock {
            get {
                object obj = ResourceManager.GetObject("labelTestColor.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        public static System.Drawing.Point labelTestColor_Location {
            get {
                object obj = ResourceManager.GetObject("labelTestColor.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size labelTestColor_Size {
            get {
                object obj = ResourceManager.GetObject("labelTestColor.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int labelTestColor_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelTestColor.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string labelTestColor_Text {
            get {
                return ResourceManager.GetString("labelTestColor.Text", resourceCulture);
            }
        }
        
        public static System.Drawing.ContentAlignment labelTestColor_TextAlign {
            get {
                object obj = ResourceManager.GetObject("labelTestColor.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        public static bool labelVideosource_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelVideosource.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Drawing.Point labelVideosource_Location {
            get {
                object obj = ResourceManager.GetObject("labelVideosource.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size labelVideosource_Size {
            get {
                object obj = ResourceManager.GetObject("labelVideosource.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int labelVideosource_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelVideosource.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video source.
        /// </summary>
        public static string labelVideosource_Text {
            get {
                return ResourceManager.GetString("labelVideosource.Text", resourceCulture);
            }
        }
        
        public static System.Drawing.Point listCodecs_Location {
            get {
                object obj = ResourceManager.GetObject("listCodecs.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size listCodecs_Size {
            get {
                object obj = ResourceManager.GetObject("listCodecs.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int listCodecs_TabIndex {
            get {
                object obj = ResourceManager.GetObject("listCodecs.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static int outputRate_Items {
            get {
                object obj = ResourceManager.GetObject("outputRate.Items", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static int outputRate_Items1 {
            get {
                object obj = ResourceManager.GetObject("outputRate.Items1", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static int outputRate_Items10 {
            get {
                object obj = ResourceManager.GetObject("outputRate.Items10", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static int outputRate_Items11 {
            get {
                object obj = ResourceManager.GetObject("outputRate.Items11", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static int outputRate_Items2 {
            get {
                object obj = ResourceManager.GetObject("outputRate.Items2", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static int outputRate_Items3 {
            get {
                object obj = ResourceManager.GetObject("outputRate.Items3", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static int outputRate_Items4 {
            get {
                object obj = ResourceManager.GetObject("outputRate.Items4", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static int outputRate_Items5 {
            get {
                object obj = ResourceManager.GetObject("outputRate.Items5", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static int outputRate_Items6 {
            get {
                object obj = ResourceManager.GetObject("outputRate.Items6", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static int outputRate_Items7 {
            get {
                object obj = ResourceManager.GetObject("outputRate.Items7", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static int outputRate_Items8 {
            get {
                object obj = ResourceManager.GetObject("outputRate.Items8", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static int outputRate_Items9 {
            get {
                object obj = ResourceManager.GetObject("outputRate.Items9", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static System.Drawing.Point outputRate_Location {
            get {
                object obj = ResourceManager.GetObject("outputRate.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size outputRate_Size {
            get {
                object obj = ResourceManager.GetObject("outputRate.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int outputRate_TabIndex {
            get {
                object obj = ResourceManager.GetObject("outputRate.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static System.Drawing.Point panel1_Location {
            get {
                object obj = ResourceManager.GetObject("panel1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size panel1_Size {
            get {
                object obj = ResourceManager.GetObject("panel1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int panel1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("panel1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static System.Windows.Forms.AnchorStyles pathForBackup_Anchor {
            get {
                object obj = ResourceManager.GetObject("pathForBackup.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        public static System.Drawing.Point pathForBackup_Location {
            get {
                object obj = ResourceManager.GetObject("pathForBackup.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size pathForBackup_Size {
            get {
                object obj = ResourceManager.GetObject("pathForBackup.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int pathForBackup_TabIndex {
            get {
                object obj = ResourceManager.GetObject("pathForBackup.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static System.Drawing.Point serialPortBaudRate_Location {
            get {
                object obj = ResourceManager.GetObject("serialPortBaudRate.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size serialPortBaudRate_Size {
            get {
                object obj = ResourceManager.GetObject("serialPortBaudRate.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int serialPortBaudRate_TabIndex {
            get {
                object obj = ResourceManager.GetObject("serialPortBaudRate.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static System.Drawing.Point serialPortName_Location {
            get {
                object obj = ResourceManager.GetObject("serialPortName.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size serialPortName_Size {
            get {
                object obj = ResourceManager.GetObject("serialPortName.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int serialPortName_TabIndex {
            get {
                object obj = ResourceManager.GetObject("serialPortName.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static bool startMinimized_AutoSize {
            get {
                object obj = ResourceManager.GetObject("startMinimized.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Drawing.Point startMinimized_Location {
            get {
                object obj = ResourceManager.GetObject("startMinimized.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size startMinimized_Size {
            get {
                object obj = ResourceManager.GetObject("startMinimized.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int startMinimized_TabIndex {
            get {
                object obj = ResourceManager.GetObject("startMinimized.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start minimized.
        /// </summary>
        public static string startMinimized_Text {
            get {
                return ResourceManager.GetString("startMinimized.Text", resourceCulture);
            }
        }
        
        public static bool startWithFullWindowedVideo_AutoSize {
            get {
                object obj = ResourceManager.GetObject("startWithFullWindowedVideo.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Windows.Forms.ImeMode startWithFullWindowedVideo_ImeMode {
            get {
                object obj = ResourceManager.GetObject("startWithFullWindowedVideo.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        public static System.Drawing.Point startWithFullWindowedVideo_Location {
            get {
                object obj = ResourceManager.GetObject("startWithFullWindowedVideo.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size startWithFullWindowedVideo_Size {
            get {
                object obj = ResourceManager.GetObject("startWithFullWindowedVideo.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int startWithFullWindowedVideo_TabIndex {
            get {
                object obj = ResourceManager.GetObject("startWithFullWindowedVideo.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start with full windowed video.
        /// </summary>
        public static string startWithFullWindowedVideo_Text {
            get {
                return ResourceManager.GetString("startWithFullWindowedVideo.Text", resourceCulture);
            }
        }
        
        public static bool startWithWindows_AutoSize {
            get {
                object obj = ResourceManager.GetObject("startWithWindows.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Drawing.Point startWithWindows_Location {
            get {
                object obj = ResourceManager.GetObject("startWithWindows.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size startWithWindows_Size {
            get {
                object obj = ResourceManager.GetObject("startWithWindows.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int startWithWindows_TabIndex {
            get {
                object obj = ResourceManager.GetObject("startWithWindows.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start with windows.
        /// </summary>
        public static string startWithWindows_Text {
            get {
                return ResourceManager.GetString("startWithWindows.Text", resourceCulture);
            }
        }
        
        public static System.Drawing.Point tabCompression_Location {
            get {
                object obj = ResourceManager.GetObject("tabCompression.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Windows.Forms.Padding tabCompression_Padding {
            get {
                object obj = ResourceManager.GetObject("tabCompression.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        public static System.Drawing.Size tabCompression_Size {
            get {
                object obj = ResourceManager.GetObject("tabCompression.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int tabCompression_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tabCompression.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression.
        /// </summary>
        public static string tabCompression_Text {
            get {
                return ResourceManager.GetString("tabCompression.Text", resourceCulture);
            }
        }
        
        public static System.Drawing.Point tabGps_Location {
            get {
                object obj = ResourceManager.GetObject("tabGps.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Windows.Forms.Padding tabGps_Padding {
            get {
                object obj = ResourceManager.GetObject("tabGps.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        public static System.Drawing.Size tabGps_Size {
            get {
                object obj = ResourceManager.GetObject("tabGps.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int tabGps_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tabGps.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS.
        /// </summary>
        public static string tabGps_Text {
            get {
                return ResourceManager.GetString("tabGps.Text", resourceCulture);
            }
        }
        
        public static System.Drawing.Point tabLocalization_Location {
            get {
                object obj = ResourceManager.GetObject("tabLocalization.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Windows.Forms.Padding tabLocalization_Padding {
            get {
                object obj = ResourceManager.GetObject("tabLocalization.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        public static System.Drawing.Size tabLocalization_Size {
            get {
                object obj = ResourceManager.GetObject("tabLocalization.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int tabLocalization_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tabLocalization.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        public static string tabLocalization_Text {
            get {
                return ResourceManager.GetString("tabLocalization.Text", resourceCulture);
            }
        }
        
        public static System.Drawing.Point tabOutput_Location {
            get {
                object obj = ResourceManager.GetObject("tabOutput.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Windows.Forms.Padding tabOutput_Padding {
            get {
                object obj = ResourceManager.GetObject("tabOutput.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        public static System.Drawing.Size tabOutput_Size {
            get {
                object obj = ResourceManager.GetObject("tabOutput.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int tabOutput_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tabOutput.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string tabOutput_Text {
            get {
                return ResourceManager.GetString("tabOutput.Text", resourceCulture);
            }
        }
        
        public static System.Windows.Forms.TabAppearance tabPageSettings_Appearance {
            get {
                object obj = ResourceManager.GetObject("tabPageSettings.Appearance", resourceCulture);
                return ((System.Windows.Forms.TabAppearance)(obj));
            }
        }
        
        public static System.Windows.Forms.DockStyle tabPageSettings_Dock {
            get {
                object obj = ResourceManager.GetObject("tabPageSettings.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        public static System.Drawing.Size tabPageSettings_ItemSize {
            get {
                object obj = ResourceManager.GetObject("tabPageSettings.ItemSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static System.Drawing.Point tabPageSettings_Location {
            get {
                object obj = ResourceManager.GetObject("tabPageSettings.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size tabPageSettings_Size {
            get {
                object obj = ResourceManager.GetObject("tabPageSettings.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int tabPageSettings_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tabPageSettings.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static System.Drawing.Point tabStartOptions_Location {
            get {
                object obj = ResourceManager.GetObject("tabStartOptions.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Windows.Forms.Padding tabStartOptions_Padding {
            get {
                object obj = ResourceManager.GetObject("tabStartOptions.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        public static System.Drawing.Size tabStartOptions_Size {
            get {
                object obj = ResourceManager.GetObject("tabStartOptions.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int tabStartOptions_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tabStartOptions.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start options.
        /// </summary>
        public static string tabStartOptions_Text {
            get {
                return ResourceManager.GetString("tabStartOptions.Text", resourceCulture);
            }
        }
        
        public static System.Drawing.Point tabVideoSource_Location {
            get {
                object obj = ResourceManager.GetObject("tabVideoSource.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Windows.Forms.Padding tabVideoSource_Padding {
            get {
                object obj = ResourceManager.GetObject("tabVideoSource.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        public static System.Drawing.Size tabVideoSource_Size {
            get {
                object obj = ResourceManager.GetObject("tabVideoSource.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int tabVideoSource_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tabVideoSource.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video source.
        /// </summary>
        public static string tabVideoSource_Text {
            get {
                return ResourceManager.GetString("tabVideoSource.Text", resourceCulture);
            }
        }
        
        public static System.Windows.Forms.AnchorStyles textBoxPath_Anchor {
            get {
                object obj = ResourceManager.GetObject("textBoxPath.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        public static System.Drawing.Point textBoxPath_Location {
            get {
                object obj = ResourceManager.GetObject("textBoxPath.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size textBoxPath_Size {
            get {
                object obj = ResourceManager.GetObject("textBoxPath.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int textBoxPath_TabIndex {
            get {
                object obj = ResourceManager.GetObject("textBoxPath.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        public static System.Drawing.Point videoSource_Location {
            get {
                object obj = ResourceManager.GetObject("videoSource.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Size videoSource_Size {
            get {
                object obj = ResourceManager.GetObject("videoSource.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        public static int videoSource_TabIndex {
            get {
                object obj = ResourceManager.GetObject("videoSource.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
    }
}
